### PR TITLE
Fixes IPv4 connectivity after host reboot

### LINKED ISSUE #756: IP4 connectivity to VMs are lost after host reboot
After fixing host reboot in https://github.com/ubicloud/ubicloud/pull/755, I noticed after `vm_host.incr_reboot` finishes and host and vm are in `wait` state, I can SSH into the VM using IP6, but not IP4. Before reboot I could ssh using both.

### PR DESCRIPTION
**Pull request by furkansahin**
Fixes #756. The issue mentions the connectivity loss after host reboot for IPv4. This is related to the ipv4 private subnet not being persistently added to the tuntap* interface. In this PR, we are simply repopulating that and getting into the rekeying sequence to also keep the private networking connectivity. Because we also lost the ip xfrm state and policy objects at the host reboot.

### CODE REVIEW

File: model/private_subnet.rb [hunk 1]
```diff
@@ -36,7 +36,7 @@ def display_state
   end
 
   include SemaphoreMethods
-  semaphore :destroy, :refresh_keys, :add_new_nic
+  semaphore :destroy, :refresh_keys, :add_new_nic, :repopulate
```
Comment (enescakir) [inline model/private_subnet.rb:39]: Do we use the `repopulate` semaphore at SubnetNexus?

Comment (furkansahin) [reply model/private_subnet.rb]: Nice catch, leftover from development

**Review by enescakir — APPROVED** [review]
LGMT on a high level. However, I'm not familiar with the low-level details.

**Review by fdr — APPROVED** [review]

**Comment by fdr** [comment]
interesting that it uses a sub-program, no objection, but what was the pro/con vs push? (I've actually been wondering if push is not valuable enough on its own to keep, but it's an idle thought so far)

**Review by pykello — APPROVED** [review]
I tested this with modified E2E CI, and it finished successfully. Thanks!

**Comment by pykello** [comment]
@furkansahin sorry, I was not careful that my other PR was based on this. I clicked the merge and now it's merged to this. Feel free to remove my commit if you don't feel comfortable.

**Comment by furkansahin** [comment]
> interesting that it uses a sub-program, no objection, but what was the pro/con vs push? (I've actually been wondering if push is not valuable enough on its own to keep, but it's an idle thought so far)

I used sub-program since in this file it is the overall convention. In this specific case we could also use push but I did not experiment with it to be fair.
