### PR TITLE
Fix physical slot with new primary

### LINKED ISSUE #4904: Replication slot deadlock after planned failover during scale-up
## Bug

After a planned failover during a Postgres scale-up, the newly promoted primary does not create replication slots for remaining standbys in `wait_catch_up`. This causes a deadlock where standbys can never catch up, and the scale-up cannot complete without manual intervention.

## Sequence of events

1. User triggers a scale-up (e.g., i8g.2xlarge → i8ge.3xlarge)
2. Convergence provisions 3 new standbys (i8ge.3xlarge). They restore from backup and enter `wait_catch_up`
3. Once enough new standbys are ready, convergence triggers a planned failover via `recycle_representative_server`
4. One of the new standbys is promoted to primary (`taking_over` label in `postgres_server_nexus.rb`)
5. In `taking_over` (line 889), all remaining standbys are reset to `synchronization_status: "catching_up"`
6. The new primary runs `configure` → `configure_hash` (`postgres_server.rb:99`) only creates physical replication slots for standbys where `synchronization_status == "ready"`
7. Since all remaining standbys are now `"catching_up"`, **no replication slots are created**
8. Old servers are pruned
9. Remaining standbys try to connect to the new primary: `ERROR: replication slot "<ubid>" specified by "primary_slot_name" does not exist on primary server`
10. `wait_catch_up` (line 606) naps until `lsn_caught_up` — but the standby can't stream WAL without a slot, so `lsn_caught_up` never becomes true
11. `wait_catch_up` only calls `representative_server.incr_configure` **after** `lsn_caught_up` succeeds (line 612), so the primary is never reconfigured to add the missing slots
12. **Deadlock**: standbys need slots to catch up, primary won't create slots until standbys are caught up

## Why this only happens during scale-up

In a normal failover without scale-up, the old standbys already had replication slots on the previous primary. Those slots persist after promotion (the configure script only drops slots not in the current list). During scale-up, the new standbys were still in `wait_catch_up` and never had slots created for them on any primary — so there are no pre-existing slots to inherit.

## Observed impact

Standbys are stuck permanently in `wait_catch_up`. The new primary has 0 streaming replicas. The scale-up cannot complete, and the resource runs without HA until manual intervention.

### PR DESCRIPTION
**Pull request by serprex**
Scaling up a 2 standby setup can get into a scenario where physical slot was created on old primary when standby reused, causing connection to new primary to fail due to slot missing

Fix this by tracking which server standby was created on, when primary doesn't match the slot needs to be recreated & id updated

alternative to #4915
fixes #4904

### CODE REVIEW

File: migrate/20260330_pg_physical_slot_ready_id.rb [hunk 1]
```diff
@@ -0,0 +1,9 @@
+# frozen_string_literal: true
+
+Sequel.migration do
+  change do
+    alter_table(:postgres_server) do
+      add_column :physical_slot_ready_id, :uuid
+    end
+  end
```
Comment (byucesoy) [inline migrate/20260330_pg_physical_slot_ready_id.rb:23]: We should also backfill the physical_slot_ready_id, so that we can safely remove physical_slot_ready column (and all the || conditionals that includes it)

Comment (serprex) [reply migrate/20260330_pg_physical_slot_ready_id.rb:23]: wasn't sure if that migration should happen here or as a followup step, I think there's some potential race, but unlikely, will do

**Comment by serprex** [comment]
I tested this pretty thoroughly: adjusted `main` to force race _(physical slots created for all standbys before failover)_, ported adjustments to this branch, & verified failover happened without errors from previous test

File: prog/postgres/postgres_server_nexus.rb [hunk 2]
```diff
@@ -401,7 +401,7 @@ def before_run
       hop_wait
     when "Failed", "NotStarted"
       if postgres_server.use_physical_slot_set?
-        postgres_server.update(physical_slot_ready: true)
+        postgres_server.update(physical_slot_ready_id: postgres_server.resource.representative_server.id)
```
Comment (byucesoy) [inline prog/postgres/postgres_server_nexus.rb:442]: This didn't got introduced in this PR, but why do we set `physical_slot_ready` or `physical_slot_ready_id` when configure is failed?

Comment (serprex) [reply prog/postgres/postgres_server_nexus.rb:442]: when primary creates slot it increments use_physical_slot on standby. this update is standby registering that signal for configure_hash to use slot that exists now
would seem tho that there's a potential race here if after creating slot primary does failover, & in meantime new primary came up when standby finally gets to configure

not sure how best to address this, primary shouldn't update standby, but ideal would be for `incr_use_physical_slot` a few lines above being able to take primary's id as parameter

Comment (byucesoy) [reply prog/postgres/postgres_server_nexus.rb:442]: If primary does failover, it would go through configure again and call `incr_use_physical_slot` on standbys with non-matching `physical_slot_ready_id`, so that shouldn't cause any problem? I didn't think about this deeply though...

File: migrate/20260313_pg_physical_slot_ready_id.rb [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+      SET physical_slot_ready_id = rep.id
+      FROM postgres_server AS rep
+      WHERE ps.physical_slot_ready
+        AND rep.resource_id = ps.resource_id
+        AND rep.is_representative
+    SQL
+
+    alter_table(:postgres_server) do
+      drop_column :physical_slot_ready
+    end
```
Comment (furkansahin) [inline migrate/20260313_pg_physical_slot_ready_id.rb]: Can you please isolate this into a 3rd commit (the very last one). This way, we would have a zero downtime deployment.
